cifar10:
  Peng2023Robust:
    gelu:
      s_low: 0.05
      s_high: 5
      c_low: -1.1
      c_high: 0
      p_low: 1
      p_high: 4
    none:
cifar100:
  Wang2023Better_WRN-70-16:
    gelu:
      s_low: 0.05
      s_high: 4
      c_low: -2.5
      c_high: -0.4
      p_low: 1
      p_high: 4
    none:
imagenet:
  Liu2023Comprehensive_Swin-L:
    gelu:
      s_low: 0.01
      s_high: 0.2
      c_low: -2
      c_high: 0
      p_low: 2
      p_high: 3
    none:
